In [1]:
import numpy as np

In [2]:
np.__version__

'1.19.2'

In [9]:
#產生等差數列：兩種方式: arange, linspace
np.arange(5) #1-dim, 0~4
np.arange(1,5) #1~4

array([1, 2, 3, 4])

In [8]:
np.linspace(1,2,5) #產生1~2 共五個數

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [16]:
#ones, zeros, empty
np.ones((3,2))
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [18]:
np.empty((2,3)) #creates an array whose initial content is random and depends on the state of the memory

array([[1., 1., 1.],
       [1., 1., 1.]])

In [27]:
#np slicing [start:stop:step] 

a = np.arange(1,7) # 1~6
a[2:5] #3,4,5 
a[-1] #6
a[:-1] # == a[0:-1], 1~5

array([1, 2, 3, 4, 5])

作業目標:
在array中，可以靈活應用索引幫助資料擷取

作業重點:
陣列的索引、切片、以及屬性，皆需要注意使用方式
陣列之中索引式由0開始請同學注意

題目:
1.生成一個等差數列，首數為0，尾數為20，公差為1的數列。

2.呈上題，將以上數列取出偶數。

3.呈1題，將數列取出3的倍數。

In [40]:
import numpy as np

#1.生成一個等差數列，首數為0，尾數為20，公差為1的數列。

#0,1,...,20

b = np.arange(0,21,1)
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [51]:
#2.呈上題，將以上數列取出偶數

c = [b[i] for i in range(0, len(b)) if b[i] % 2 == 0]
c

#或是 b[::2]
#b[b%2 == 0]

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20]

In [53]:
#3.呈1題，將數列取出3的倍數

d = [b[i] for i in range(0, len(b)) if b[i] % 3 == 0]
d

#或是b[::3]

[0, 3, 6, 9, 12, 15, 18]

In [54]:
b[::2]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [56]:
b[::3]

array([ 0,  3,  6,  9, 12, 15, 18])

In [58]:
b[b%2 == 0]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [59]:
b[b%3 == 0]

array([ 0,  3,  6,  9, 12, 15, 18])