In [18]:
import numpy as np
a = np.arange(1,10).reshape(3,3)
a


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
#將多維陣列降成一維
#flatten: 返回一份copy, 對此copy做更改對原本不影響
a.flatten()
a.flatten()[0] = 200
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
#ravel()：對此做更改對原本會影響
a.ravel()
a.ravel()[0] = 200
a

array([[200,   2,   3],
       [  4,   5,   6],
       [  7,   8,   9]])

In [25]:
#reshape()

a.reshape(1,9)

array([[200,   2,   3,   4,   5,   6,   7,   8,   9]])

In [30]:
np.reshape(a, (1,9))

array([[200,   2,   3,   4,   5,   6,   7,   8,   9]])

In [36]:
#resize()
np.resize(a,(1,10)) #超出的部分補上第0個值

array([[200,   2,   3,   4,   5,   6,   7,   8,   9, 200]])

In [122]:
#axis

b = np.arange(1,13).reshape(4,3)
b
#這是個維度只有2的陣列（行、列）

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [39]:
np.sum(b, axis = 0) #axis = 0, 行
#沿著行相加，回傳一維陣列

array([22, 26, 30])

In [40]:
np.sum(b, axis = 1) 

array([ 6, 15, 24, 33])

In [43]:
c = np.arange(1,13).reshape(2,3,2)
c #現在變成三維陣列了 

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [48]:
np.sum(c, axis = 1)

array([[ 9, 12],
       [27, 30]])

In [58]:
#concatenate(): 合併，by default, axis = 0

A = np.array([[1,2], [3,4]])
B = np.array([[5,6]])

np.concatenate((A,B), axis = 0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
#陣列stack(), hstack() （axis=1), vstack()(axis=0)

In [61]:
C = np.array([[1,2], [3,4], [5,6]])
D = np.array([[7,8]])

np.vstack((C,D))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [66]:
#stack()要維度相同才能合併, 合併之後會增加一個dim
np.stack(C, axis = 0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [67]:
#array_split()、hsplit()、vsplit():  分割陣列

#hsplit() 沿著橫軸拆分
C = np.array([[1,2], [3,4], [5,6]])
np.hsplit(C,2)

[array([[1],
        [3],
        [5]]),
 array([[2],
        [4],
        [6]])]

In [70]:
E = np.array([[1,2,3],[4,5,6],[7,8,9]])
np.vsplit(E,3)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]

In [75]:
x = np.arange(8) # 0~7
np.array_split(x, 3)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7])]

In [80]:
#陣列的迭代

for row in C:
    print(row)

[1 2]
[3 4]
[5 6]


In [81]:
for i in C.flat: #配合.flat印出每個元素
    print(i)

1
2
3
4
5
6


In [93]:
#反回最大最小值：amax()、amin()、max()、min()
# [[1,2,3],[4,5,6],[7,8,9]] 
np.amax(E, axis = 0) #[7,8,9]
np.amin(E, axis = 1) #[1,4,7]

array([1, 4, 7])

In [94]:
np.amax(E, axis = 0)

array([7, 8, 9])

In [98]:
#argmax/argmin: 回傳index
np.argmax(E, axis = 0) #[2,2,2] 因為都在第二個位置最大
np.argmax(E, axis = 1) #[2,2,2]
np.argmax(E) #8, 因為是最後一個

8

In [101]:
#where()/where(condition,x,y)

a = np.array([1,2,3,4,5])
a[np.where(a > 1)] #np.where(a>1)回傳位置



array([2, 3, 4, 5])

In [104]:
b = np.array([100,25,34,79,48])

np.where(b>60, ['pass'], ['fail'])

array(['pass', 'fail', 'fail', 'pass', 'fail'], dtype='<U4')

In [106]:
#nonzero = where(array!=0)

np.nonzero(b) #回傳位置
b[np.nonzero(b)]

array([100,  25,  34,  79,  48])

In [108]:
#排序：sort(), argsort()（回傳位置）

c = np.array([2,1,-1,34,78,-90])
np.argsort(c)

array([5, 2, 1, 0, 3, 4])

題目：

array1 = np.array(range(30))

1.將上列陣列(array1)，轉成維度為(5X6)的 array，順序按列填充。(hint:order="F")

2.呈上題的 array，找出被 6 除餘 1 的數的索引

In [131]:
import numpy as np

array1 = np.array(range(30)) #0~29

#1. 將上列陣列(array1)，轉成維度為(5X6)的 array，順序按列填充。(hint:order="F")
array1.reshape(5,6)



array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [133]:
#2.呈上題的 array，找出被 6 除餘 1 的數的索引


array2 = array1.reshape(5,6)

np.where(array2 % 6 == 1 )


(array([0, 1, 2, 3, 4]), array([1, 1, 1, 1, 1]))