In [9]:
import numpy as np

#np.maximum ( np.where(x1 >= x2, x1, x2))

A = np.array([3,2,3])
B = np.array([1,2,4])
np.maximum(A,B)

array([3, 2, 4])

In [16]:
np.percentile(A,25)

2.5

english_score = np.array([55,89,76,65,48,70])

math_score = np.array([60,85,60,68,np.nan,60])

chinese_score = np.array([65,90,82,72,66,77])

上 3 列共六位同學的英文、數學、國文成績，第一個元素代表第一位同學，

舉例第一位同學英文 55 分、數學 60 分、國文 65 分，

今天第五位同學因某原因沒來考試，導致數學成績缺值，運用上列數據回答下列問題。

1.請計算各科成績平均、最大值、最小值、標準差，其中數學缺一筆資料可忽略？

2.第五位同學補考數學後成績為 55，請計算補考後數學成績平均、最大值、最小值、標準差？

3.用補考後資料找出與國文成績相關係數最高的學科？

In [23]:
import numpy as np

english_score = np.array([55,89,76,65,48,70])
math_score = np.array([60,85,60,68,np.nan,60])
chinese_score = np.array([65,90,82,72,66,77])

#Q1

#mean

np.nanmean(english_score)
np.nanmean(math_score)
np.nanmean(chinese_score)


#max

np.nanmax(english_score)
np.nanmax(math_score)
np.nanmax(chinese_score)

#min

np.nanmin(english_score)
np.nanmin(math_score)
np.nanmin(chinese_score)

#sd

np.nanstd(english_score)
np.nanstd(math_score)
np.nanstd(chinese_score)

8.825468196582484

In [25]:
#Q2


math_score[np.isnan(math_score)] = 55
math_score

#mean

np.mean(math_score)

#max

np.max(math_score)

#min

np.min(math_score)

#std

np.std(math_score)

9.860132971832694

In [33]:
#Q3 : English

np.corrcoef(chinese_score, english_score)

array([[1.        , 0.97792828],
       [0.97792828, 1.        ]])

In [34]:
np.corrcoef(chinese_score, math_score)

array([[1.        , 0.74056803],
       [0.74056803, 1.        ]])