In [16]:
import numpy as np

#np.dot, np.matmul, @: matrix multiplication
#np.inner: inner product
#np.outer

A = np.array([[1,2,3], [4,5,6]]) #2 by 3
B = np.array([[4,5,6], [7,8,9], [10,11,0]]) #3 by 3

np.dot(A,B) # 2 by 3
A @ B
np.matmul(A,B)

array([[ 48,  54,  24],
       [111, 126,  69]])

In [18]:
#np.trace
np.trace(B)

12

In [20]:
#determinant

np.linalg.det(B)

36.00000000000003

In [21]:
#inverse
np.linalg.inv(B)

array([[-2.75      ,  1.83333333, -0.08333333],
       [ 2.5       , -1.66666667,  0.16666667],
       [-0.08333333,  0.16666667, -0.08333333]])

In [22]:
#transpose
np.transpose(A)

array([[1, 4],
       [2, 5],
       [3, 6]])

array1 = np.array([[10, 8], [3, 5]])

1.運用上列array計算反矩陣，乘上原矩陣，並觀察是否為單位矩陣?

2.運用上列array計算特徵值、特徵向量?

3.運用上列array計算SVD?

In [27]:
import numpy as np

array1 = np.array([[10,8], [3,5]])

#Q1

#inverse
inv_array1 = np.linalg.inv(array1)

#verify
inv_array1  @ array1

array([[1.00000000e+00, 5.55111512e-17],
       [0.00000000e+00, 1.00000000e+00]])

In [37]:
#Q2

w, v = np.linalg.eig(array1)

w #eigenvalues


array([13.,  2.])

In [38]:
v #eigenvectors

array([[ 0.93632918, -0.70710678],
       [ 0.35112344,  0.70710678]])

In [34]:
#Q3
u, s, vh = np.linalg.svd(array1)
u

array([[-0.91663818, -0.39971796],
       [-0.39971796,  0.91663818]])

In [35]:
s

array([13.94721714,  1.86417116])

In [36]:
vh

array([[-0.74319741, -0.6690722 ],
       [-0.6690722 ,  0.74319741]])